env = Environment(CPPPATH="../include")

src_files =[
	"dragon/lang/Object.cc",
	"dragon/lang/Throwable.cc",
	"dragon/lang/Exception.cc",
	"dragon/lang/RuntimeException.cc",
	"dragon/lang/IndexOutOfBoundsException.cc",
	"dragon/lang/NullPointerException.cc",
	"dragon/lang/Math.cc",
	"dragon/lang/internal/platform_win32.cc",
	"dragon/lang/String.cc"
]

env.SharedLibrary('dragon', src_files)


