# Copyright 2013 the original author or authors.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#
# **********************************************************************
# Author:      Owen Wu/wcw/yubing
# Email:       yubing744@163.com
# Created:     2013/03/31
# **********************************************************************
 
LIBRARY_FLAGS = {
  'all' : {
     'LIBS' : ['cppunit', "dragon"]	
  },
  'gcc': {
	'CPPPATH' : [
		"../include"
	],
	'LIBPATH' : [
		"../lib/gcc"				
	],
	'LIBS' : [],
	'CXXFLAGS' : [],
	'CPPDEFINES' : ['DRAGON_SHARED', 'BUILDING_DRAGON_SHARED'],
	'ARFLAGS' : [],	
	'LINKFLAGS' : []
  },
  'msvc': {
	'CPPPATH' : [
		"../include",
	],
	'LIBPATH' : [
		"../lib/msvc"			
	],
	'LIBS' : [],
	'CXXFLAGS' : ['/EHsc'],	
	'CPPDEFINES' : ['BUILDING_DRAGON_SHARED'],
	'ARFLAGS' : [],
	'LINKFLAGS' : []	
  }
}

def Build(env):
	toolchain = env['toolchain'] 
	
	env.Append(CPPPATH = LIBRARY_FLAGS[toolchain]['CPPPATH'])
	env.Append(LIBPATH = LIBRARY_FLAGS[toolchain]['LIBPATH'])
	env.Append(LIBS = LIBRARY_FLAGS[toolchain]['LIBS'])
	env.Append(CXXFLAGS = LIBRARY_FLAGS[toolchain]['CXXFLAGS'])
	env.Append(CPPDEFINES = LIBRARY_FLAGS[toolchain]['CPPDEFINES'])
	env.Append(ARFLAGS = LIBRARY_FLAGS[toolchain]['ARFLAGS'])
	env.Append(LINKFLAGS = LIBRARY_FLAGS[toolchain]['LINKFLAGS'])
		
	src_files =[
#		"dragon/lang/Object.cc",
#		"dragon/lang/Throwable.cc",
#		"dragon/lang/Exception.cc",
#		"dragon/lang/RuntimeException.cc",
#		"dragon/lang/IndexOutOfBoundsException.cc",
#		"dragon/lang/NullPointerException.cc",
		"dragon/lang/Math.cc"
#		"dragon/lang/internal/platform_win32.cc",
#		"dragon/lang/String.cc"
	]
	
	lib_files = env.SharedLibrary('dragon', source=src_files)
	env.Install('../lib/' + toolchain, lib_files)	
		

# We disable deprecation warnings because we need to be able to use
# env.Copy without getting warnings for compatibility with older
# version of scons.  Also, there's a bug in some revisions that
# doesn't allow this flag to be set, so we swallow any exceptions.
# Lovely.
try:
  SetOption('warn', 'no-deprecated')
except:
  pass

Import('env')
Build(env.Copy())

