# -*- python -*-
# Copyright 2013 the original author or authors.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#
# **********************************************************************
# Author:      Owen Wu/wcw/yubing
# Email:       yubing744@163.com
# Created:     2013/03/31
# **********************************************************************
 
LIBRARY_FLAGS = {
  'all' : {
     'LIBS' : ['cppunit', "dragon"]	
  },
  'gcc': {
	'CPPPATH' : [
		"/usr/local/include",
		"../include"
	],
	'LIBPATH' : [
		"/usr/local/lib",
		"../lib"				
	],
	'LIBS' : ['cppunit', "dragon"],
	'LINKFLAGS' : []
  },
  'msvc': {
	'CPPPATH' : [
		"../include",
		"../../third_party/cppunit-1.10.2/include"
	],
	'LIBPATH' : [
		"../../third_party/cppunit-1.10.2/lib",
		"../lib"			
	],
	'LIBS' : ['cppunit_dll_x64', "dragon"],
	'LINKFLAGS' : []	
  }
}

def Build(env):
	toolchain = env['toolchain'] 
	
	include_path = LIBRARY_FLAGS[toolchain]['CPPPATH']
	lib_path = LIBRARY_FLAGS[toolchain]['LIBPATH']
	libs = LIBRARY_FLAGS[toolchain]['LIBS']
	link_flags = LIBRARY_FLAGS[toolchain]['LINKFLAGS']
	
	src_files = Split("""
		dragon/lang/ObjectTest.cc
		dragon/lang/StringTest.cc
		dragon/lang/MathTest.cc
		TestMain.cc
	""")
	
	if (link_flags and len(link_flags)>0):
		env.Append(LINKFLAGS = link_flags)
	
	test_files = env.Program(target='dragon_test', source=src_files, LIBS=libs, LIBPATH=lib_path)
	testfilename = str(test_files[0])
	Command('../build/' + testfilename, testfilename, Copy("$TARGET", "$SOURCE")) 


# We disable deprecation warnings because we need to be able to use
# env.Copy without getting warnings for compatibility with older
# version of scons.  Also, there's a bug in some revisions that
# doesn't allow this flag to be set, so we swallow any exceptions.
# Lovely.
try:
  SetOption('warn', 'no-deprecated')
except:
  pass
 
Import('env')
Build(env.Copy())

