// GLSL shader autogenerated by dragon3d_cg2glsl.py.
#if defined(VERTEX)
// glesv output by Cg compiler
// cgc version 3.1.0013, build date Apr 18 2012
// command line args: -profile glesv -quiet
//vendor NVIDIA Corporation
//version 3.1.0.13
//profile glesv
//program main_vertex
//semantic main_vertex.modelViewProj
//var float4x4 modelViewProj :  : _modelViewProj1[0], 4 : 1 : 1
//var float4 position : $vin.POSITION : POSITION : 0 : 1
//var float4 color : $vin.COLOR : COLOR : 2 : 1
//var float4 oPosition : $vout.POSITION : HPOS : 3 : 1
//var float4 oColor : $vout.COLOR : COLOR : 4 : 1

precision mediump float;

vec4 _oPosition1;
uniform vec4 _modelViewProj1[4];
vec4 _r0005;
attribute vec4 POSITION;
attribute vec4 COLOR;
varying vec4 COL0;

 // main procedure, the original name was main_vertex
void main()
{

    vec4 _oColor;

    _r0005 = POSITION.x*_modelViewProj1[0];
    _r0005 = _r0005 + POSITION.y*_modelViewProj1[1];
    _r0005 = _r0005 + POSITION.z*_modelViewProj1[2];
    _r0005 = _r0005 + POSITION.w*_modelViewProj1[3];
    _oPosition1 = _r0005;
    _oColor = COLOR;
    gl_Position = _r0005;
    COL0 = COLOR;
} // main end

#elif defined(FRAGMENT)
// glesf output by Cg compiler
// cgc version 3.1.0013, build date Apr 18 2012
// command line args: -profile glesf -quiet
//vendor NVIDIA Corporation
//version 3.1.0.13
//profile glesf
//program main_fragment
//var float4 color : $vin.COLOR : COLOR : 0 : 1
//var float4 main_fragment : $vout.COLOR : COL : -1 : 1

precision mediump float;

varying vec4 COL0;

 // main procedure, the original name was main_fragment
void main()
{


    gl_FragColor = COL0;
    return;
} // main end

#endif
