# -*- python -*-
#/******************************************************************************
# * Copyright (c) 2004, 2009 Lothar Werzinger.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v1.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-v10.html
# *****************************************************************************/ 


import os.path
import sys

import platform
import re
import subprocess
import sys
import os

from os.path import join, dirname, abspath
from types import DictType, StringTypes
root_dir = dirname(File('SConstruct').rfile().abspath)
src_dir = join(root_dir, 'src')
sys.path.insert(0, join(root_dir, 'tools/SconsBuilder'))

import SconsBuilder
import SconsBuilderConfig


# add our command line options
SconsBuilder.addCommandLineOptions()

SConscript('./src/SConscript')

